blank_issues_enabled: true
contact_links:
  - name: Ask a question, share an idea, or join a conversation
    url: https://github.com/aldrichtr/infraspective/discussions
    about: Please join the discussion
