
function Invoke-PoshspecExpression {
    <#
    .SYNOPSIS
        Executes a Pester 'It' block using values generated by Get-PoshspecParam
    .DESCRIPTION
        Execute a Pester It block.  The expression and
    .EXAMPLE
        Invoke-PoshspecExpression -InputObject (
            [pscustomobject]@{
                Name = "File 'C:\Temp' Should -Exist"
                Expression = "'C:\Temp' | Should -Exist"
            }
        )
    .NOTES
        This function was originally part of the [poshspec](https://github.com/Ticketmaster/poshspec) module.  It has
        been updated to conform with Pester v5 which added a "Discover" and "Run" phase that changed the way variables
        are used.
    #>
    [CmdletBinding()]
    param(
        # Poshspec Param Object
        [Parameter(Mandatory, Position = 0)]
        [PSCustomObject]
        $InputObject
    )

    Write-Debug "Invoking 'it' block with expression: $($InputObject.Expression)"
    It $InputObject.Name -TestCases @(
        @{command = $InputObject.Expression }
    ) {
        & $command
    }
}
