# Github action workflow to build the infraspective module

name: Build pipeline

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    name: Compile individual files into Module and Manifest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Ensure we checkout the buildtools git submodule
          submodules: recursive

      # Bootstrap the build tools by installing PSDepend2
      # PSDepend2 reads modules from 'requirements.psd1' and installs them
      # according to the options in the file and/or the command line.
      - name: Install required modules
        run: |
          $current_user_mod_path = ($env:PSModulePath -split ';')[0]
          Write-Host "PowerShell Modules in $current_user_mod_path"

          Set-PSRepository psgallery -InstallationPolicy trusted
          Write-Host -ForegroundColor Green "Installing PSDepend2"
          Install-Module PSDepend2 -Scope CurrentUser -Confirm:$false -Force
          Write-Host -ForegroundColor Green "Now using PSDepend2 to install the rest of the required Modules:"
          Import-Module PSDepend2
          Invoke-PSDepend -Path "." -Recurse:$true -Tags 'ci' -Test | Select Dependency* | Write-Host -ForegroundColor Blue

          Invoke-PSDepend -Path "." -Recurse:$true -Confirm:$false -Target 'CurrentUser' -Tags 'ci'

      # The Configure task ensures that directories, files and variables
      # are present before the other tasks are run.
      - name: Configure the project
        run: Invoke-Build Configure

      # Run Pester Tests on files in source directory
      - name: Run UnitTests
        run: Invoke-Build UnitTest

      # Now create the Module and Manifest
      - name: Compile module and manifest
        if: ${{ success() }}
        run: Invoke-Build Stage
