name: Clean up old workflow runs

on:
  workflow_dispatch:
    inputs:
      interval:
        description: Time interval (only seconds supported for now)
        required: true
        default: 'seconds'
        type: choice
        options:
          - seconds
      time_value:
        description: Time value (8640 sec == 1 day)
        required: true
        default: 8640
        type: number


jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: Delete workflow runs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Delete workflow runs
        uses: MajorScruffy/delete-workflow-runs@v0.1
        id: delete-workflow-runs
        with:
          repository: aldrichtr/infraspective
          ## 8640 seconds == 1 day
          older-than-seconds: ${{ inputs.time_value }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
