name: Move new items into the proper projects

on:
  items:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened

jobs:
  Repo:
    name: Add new items to the local repository project
    runs-on: ubuntu-latest
    steps:
      - name: Add the item to the New column
        uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Infrastructure Testing Framework
          column: New
          repo-token: ${{ secrets.ACTION_ADDTOPROJECT }}
  Beta:
    name: Add item to project beta
    runs-on: ubuntu-latest
    steps:
      - name: Add item to project beta
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/aldrichtr/projects/4
          github-token: ${{ secrets.ACTION_ADDTOPROJECT }}
