name: Move new issues into the proper projects

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  Repo:
    name: Add new issues to the local repository project
    runs-on: ubuntu-latest
    steps:
      - name: Add the issue to the Backlog project ForReview
        uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Backlog
          column: For Review
          repo-token: ${{ secrets.ACTION_ADDTOPROJECT }}
  Personal:
    name: Add issue to my personal project management space
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to my personal project management space
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/aldrichtr/projects/1
          github-token: ${{ secrets.ACTION_ADDTOPROJECT }}
