name: Update main infraspective project board
# This workflow ensures that the main project board gets updated when any issue or pr does
# When an issue is created or reopened, it is given the Status of 'New'
# When a pr is created, it is given the Status of InProgress and added to the current iteration
# When an issue or pr is closed, they are given the Status of 'Closed'
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - closed

env:
  project_number: 4
  project_token: ${{ secrets.ACTION_ADDTOPROJECT }}
  project_current_iteration: '[{\"name\": \"Iteration\",\"type\": \"iteration\",\"value\": \"@current\"}]'

jobs:
  issue_opened_or_reopened:
    name: New issue
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to New
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: 'New'
  issue_closed:
    name: Close issue
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Moved issue to Closed
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: 'Closed'
  pr_opened_or_reopened_or_reviewrequested:
    name: New PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
    steps:
      - name: Move PR to In Progress
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: 'InProgress'
      - name: Add to current iteration
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          operation_mode: custom_field
          custom_field_values: ${{ env.project_current_iteration }}
  pr_closed:
    name: Close PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Move PR to Closed
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ env.project_token }}
          user: aldrichtr
          project_id: ${{ env.project_number}}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: 'Closed'
