name: Update main project board

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - closed


jobs:
  issue_opened_or_reopened:
    name: New issue
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to New
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.ACTION_ADDTOPROJECT }}
          user: aldrichtr
          project_id: 4
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: 'New'
  issue_closed:
    name: Close issue
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Moved issue to Closed
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.ACTION_ADDTOPROJECT }}
          user: aldrichtr
          project_id: 4
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: 'Closed'
  pr_opened_or_reopened_or_reviewrequested:
    name: New PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
    steps:
      - name: Move PR to In Progress
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.ACTION_ADDTOPROJECT }}
          user: aldrichtr
          project_id: 4
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: 'InProgress'
  pr_closed:
    name: Close PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Move PR to Closed
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.ACTION_ADDTOPROJECT }}
          user: aldrichtr
          project_id: 4
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: 'Closed'
