name: Move new issues into Backlog
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Backlog
          column: For Review
          repo-token: ${{ secrets.GH_TOKEN }}
